import type { ProviderStreamChunk } from '@mission-control/protocol';
import type { ProviderAdapter, ProviderAdapterContext, ProviderTurnRequest } from './provider-turn-types.js';

export function createLocalCodingProvider(): ProviderAdapter {
    return {
        async *streamTurn(request, context) {
            const prompt = lastUserPrompt(request);
            for (const chunk of chunksForPrompt(request, context, prompt)) {
                if (context.signal.aborted) {
                    return;
                }
                yield chunk;
            }
        },
    };
}

function chunksForPrompt(
    request: ProviderTurnRequest,
    context: ProviderAdapterContext,
    prompt: string,
): readonly ProviderStreamChunk[] {
    if (hasToolResultMessage(request)) {
        return [completedChunk(request, context.attempt, 'local deterministic coding turn complete')];
    }
    if (prompt.toLowerCase().includes('deterministic patch')) {
        const patch = addFilePatch('.mission-control-coding-agent.txt', 'generated by mission-control');
        const chunks: ProviderStreamChunk[] = [
            textChunk(request, 1, 'I can apply a deterministic patch.'),
            toolChunk(request, 2, 'local_patch_call', 'file.patch', JSON.stringify({ patch })),
        ];
        if (prompt.toLowerCase().includes('test')) {
            chunks.push(
                toolChunk(
                    request,
                    3,
                    'local_command_call',
                    'command.run',
                    JSON.stringify({
                        command: 'node',
                        args: ['--eval', "console.log('mission-control command.run harness ok')"],
                    }),
                ),
            );
        }
        chunks.push(completedChunk(request, chunks.length + 1, 'local deterministic coding turn complete'));
        return chunks;
    }
    const content = `received prompt: ${prompt}`;
    return [textChunk(request, context.attempt, content), completedChunk(request, context.attempt + 1, content)];
}

function lastUserPrompt(request: ProviderTurnRequest): string {
    return [...request.messages].reverse().find((message) => message.role === 'user')?.content ?? '';
}

function hasToolResultMessage(request: ProviderTurnRequest): boolean {
    return request.messages.some((message) => message.role === 'tool');
}

function textChunk(request: ProviderTurnRequest, sequence: number, delta: string): ProviderStreamChunk {
    return {
        kind: 'text_delta',
        requestId: request.requestId,
        sequence,
        delta,
    };
}

function toolChunk(
    request: ProviderTurnRequest,
    sequence: number,
    toolCallId: string,
    toolName: string,
    argumentsJson: string,
): ProviderStreamChunk {
    return {
        kind: 'tool_call_completed',
        requestId: request.requestId,
        sequence,
        toolCall: {
            toolCallId,
            toolName,
            argumentsJson,
        },
    };
}

function completedChunk(request: ProviderTurnRequest, sequence: number, content: string): ProviderStreamChunk {
    return {
        kind: 'response_completed',
        requestId: request.requestId,
        sequence,
        message: {
            messageId: `message_${request.turnId}_${sequence}`,
            role: 'assistant',
            content,
        },
        finishReason: 'stop',
    };
}

function addFilePatch(path: string, content: string): string {
    return [
        `diff --git a/${path} b/${path}`,
        '--- /dev/null',
        `+++ b/${path}`,
        '@@ -0,0 +1 @@',
        `+${content}`,
        '',
    ].join('\n');
}
