pub(crate) const SESSION_LOG_HEADER_KIND: &str = "mission-control.session-log";
pub(crate) const SESSION_EVENT_RECORD_KIND: &str = "mission-control.session-event";
pub(crate) const SESSION_LOG_RECORD_VERSION: u64 = 1;
pub(crate) const DURABLE_EVENT_DURABILITY: &str = "durable";
pub(crate) const EVENT_DURABILITIES: &[&str] = &["durable", "ephemeral"];
pub(crate) const AGENT_EVENT_TYPES: &[&str] = &[
    "session.started",
    "session.stopped",
    "task.started",
    "task.progress",
    "task.completed",
    "task.failed",
    "permission.requested",
    "approval.requested",
    "approval.updated",
    "approval.blocked",
    "approval.resumed",
    "prompt.admitted",
    "prompt.promoted",
    "run.command.received",
    "run.started",
    "run.completed",
    "run.interrupted",
    "run.idle",
    "run.failed",
    "run.blocked",
    "native.status",
    "native.warning",
    "log",
    "graph.started",
    "graph.completed",
    "graph.failed",
    "graph.cancelled",
    "attempt.started",
    "attempt.completed",
    "attempt.failed",
    "node.waiting",
    "node.started",
    "node.progress",
    "node.completed",
    "node.failed",
    "node.cancelled",
    "decision.selected",
    "policy.blocked",
    "model.call.started",
    "model.call.completed",
    "model.call.failed",
    "tool.started",
    "tool.completed",
    "tool.failed",
    "command.started",
    "command.completed",
    "command.failed",
    "command.timed_out",
    "file.diff.proposed",
    "file.diff.applied",
    "workflow.transitioned",
];
