export const legacyImportTableSql = [
    `CREATE TABLE IF NOT EXISTS sessions (
        session_id TEXT PRIMARY KEY,
        status TEXT NOT NULL,
        awaiting_reason TEXT,
        primary_wait_id TEXT,
        root_session_id TEXT,
        parent_session_id TEXT,
        workspace_path TEXT,
        provider_id TEXT,
        model_id TEXT,
        title TEXT,
        total_input_tokens INTEGER NOT NULL DEFAULT 0,
        total_output_tokens INTEGER NOT NULL DEFAULT 0,
        total_cost_usd TEXT,
        last_event_seq INTEGER NOT NULL DEFAULT 0,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        last_activity_at TEXT NOT NULL,
        stopped_at TEXT,
        failed_at TEXT,
        legacy_jsonl_path TEXT,
        imported_at TEXT,
        exported_at TEXT,
        metadata_json TEXT
    )`,
    `CREATE TABLE IF NOT EXISTS session_event_sequences (
        session_id TEXT PRIMARY KEY,
        next_seq INTEGER NOT NULL DEFAULT 0,
        updated_at TEXT NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS session_events (
        session_id TEXT NOT NULL,
        seq INTEGER NOT NULL,
        event_id TEXT NOT NULL,
        type TEXT NOT NULL,
        timestamp TEXT NOT NULL,
        run_id TEXT,
        turn_id TEXT,
        causation_id TEXT,
        correlation_id TEXT,
        payload_json TEXT NOT NULL,
        PRIMARY KEY (session_id, seq),
        UNIQUE (event_id)
    )`,
    `CREATE TABLE IF NOT EXISTS mission_runs (
        run_id TEXT PRIMARY KEY,
        mission_id TEXT NOT NULL,
        parent_run_id TEXT,
        session_id TEXT,
        child_agent_kind TEXT,
        child_agent_id TEXT,
        child_session_ids_json TEXT,
        retry_state_json TEXT,
        status TEXT NOT NULL,
        prompt TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        started_at TEXT,
        ended_at TEXT,
        completed_at TEXT,
        failed_at TEXT,
        cancelled_at TEXT,
        passthrough_json TEXT NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS legacy_session_imports (
        import_id TEXT PRIMARY KEY,
        source_path TEXT NOT NULL,
        source_kind TEXT NOT NULL,
        checksum TEXT NOT NULL,
        imported_event_count INTEGER NOT NULL DEFAULT 0,
        imported_at TEXT NOT NULL,
        diagnostics_json TEXT,
        UNIQUE (source_path, checksum)
    )`,
] as const;
