/**
 * Local-echo AI-SDK model (Phase 5 / flip-default enabler, strategy C).
 *
 * The `local/local-echo` sandbox provider is otherwise a FLAT-path-only `ProviderAdapter`
 * (`local-coding-provider.ts`) — it has no network and no AI-SDK mapping, so the graph engine
 * rejected it ("cannot drive provider 'local'"). That blocked the blanket flip: every
 * credential-free run (no auth configured, the test suite's default) falls back to
 * `local/local-echo`, which only the flat engine drives.
 *
 * This module is the scripted AI-SDK `LanguageModelV3` that lets the graph engine drive
 * `local/local-echo` too. It reproduces `local-coding-provider.ts`'s DETERMINISTIC branching so a
 * graph run on the local sandbox behaves the same as a flat run:
 *   - a turn that already carries a tool-result message → finalize immediately;
 *   - a "deterministic patch" prompt → propose a `file.patch` tool call (and `command.run` when
 *     the prompt also says "test"), letting the graph's self-edge drive the multi-step loop;
 *   - anything else → emit `received prompt: <text>` and finalize.
 *
 * It is a pure scripted model (no network, no key) — so credential-free graph runs work, which
 * unblocks the flip-default and lets the credential-free flat-path tests run on the graph engine
 * (verifying parity) without needing real provider credentials.
 */
import {
    type LanguageModelV3,
    type LanguageModelV3CallOptions,
    type LanguageModelV3FilePart,
    type LanguageModelV3Message,
    type LanguageModelV3StreamPart,
    type LanguageModelV3TextPart,
    UnsupportedFunctionalityError,
} from '@ai-sdk/provider';

export type LocalEchoSdkModelOptions = {
    readonly provider?: string;
    readonly modelId?: string;
};

const LOCAL_PROVIDER = 'local';
const LOCAL_MODEL_ID = 'local-echo';

/** Build the scripted local-echo `LanguageModelV3` the graph engine drives for `local/local-echo`. */
export function createLocalEchoSdkModel(options: LocalEchoSdkModelOptions = {}): LanguageModelV3 {
    const provider = options.provider ?? LOCAL_PROVIDER;
    const modelId = options.modelId ?? LOCAL_MODEL_ID;
    return {
        specificationVersion: 'v3',
        provider,
        modelId,
        supportedUrls: {},
        async doGenerate() {
            // The graph path uses `streamText` (doStream); the non-streaming path is not exercised.
            throw new UnsupportedFunctionalityError({
                functionality: 'local-echo doGenerate',
                message: 'the local-echo scripted model does not support doGenerate (graph path uses doStream)',
            });
        },
        async doStream(callOptions: LanguageModelV3CallOptions) {
            const chunks = chunksForLocalEcho(callOptions.prompt);
            return { stream: readableStreamFromChunks(chunks) };
        },
    };
}

/**
 * Reproduce `local-coding-provider.ts`'s deterministic branching as AI-SDK stream parts. The
 * prompt is read from the SDK's standardized message list (the last user message's text; the
 * presence of a tool-result message marks a resumed multi-step turn).
 */
function chunksForLocalEcho(prompt: readonly LanguageModelV3Message[]): readonly LanguageModelV3StreamPart[] {
    if (prompt.some((message) => message.role === 'tool')) {
        return finalizeChunks('local deterministic coding turn complete');
    }
    const userPrompt = lastUserPromptText(prompt);
    if (userPrompt.toLowerCase().includes('deterministic patch')) {
        const patch = addFilePatch('.mission-control-coding-agent.txt', 'generated by mission-control');
        const parts: LanguageModelV3StreamPart[] = [
            ...textChunks('I can apply a deterministic patch.'),
            ...toolCallChunks('local_patch_call', 'file.patch', { patch }),
        ];
        if (userPrompt.toLowerCase().includes('test')) {
            parts.push(
                ...toolCallChunks('local_command_call', 'command.run', {
                    command: 'node',
                    args: ['--eval', "console.log('mission-control command.run harness ok')"],
                }),
            );
        }
        // A tool-proposing turn finishes as `tool-calls` so the graph's self-edge re-enters the LLM
        // actor for the follow-up turn (which then sees the tool-result message and finalizes).
        parts.push(finishChunk('tool-calls'));
        return parts;
    }
    const content = `received prompt: ${userPrompt}`;
    return [...textChunks(content), finishChunk('stop')];
}

function lastUserPromptText(prompt: readonly LanguageModelV3Message[]): string {
    for (let index = prompt.length - 1; index >= 0; index -= 1) {
        const message = prompt[index];
        if (message !== undefined && message.role === 'user') {
            return contentToText(message.content);
        }
    }
    return '';
}

/** Flatten a user message's content parts to their concatenated text. */
function contentToText(content: readonly (LanguageModelV3TextPart | LanguageModelV3FilePart)[]): string {
    return content
        .map((part) => (part.type === 'text' ? part.text : ''))
        .filter((text) => text.length > 0)
        .join('');
}

function textChunks(delta: string): readonly LanguageModelV3StreamPart[] {
    return [
        { type: 'stream-start', warnings: [] },
        { type: 'text-start', id: 'local_text' },
        { type: 'text-delta', id: 'local_text', delta },
        { type: 'text-end', id: 'local_text' },
    ];
}

function toolCallChunks(
    toolCallId: string,
    toolName: string,
    input: Record<string, unknown>,
): readonly LanguageModelV3StreamPart[] {
    const inputJson = JSON.stringify(input);
    return [
        { type: 'tool-input-start', id: toolCallId, toolName },
        { type: 'tool-input-delta', id: toolCallId, delta: inputJson },
        { type: 'tool-input-end', id: toolCallId },
        { type: 'tool-call', toolCallId, toolName, input: inputJson },
    ];
}

/** A finalize-only turn (no text/tool deltas) — used when a resumed turn should just stop. */
function finalizeChunks(content: string): readonly LanguageModelV3StreamPart[] {
    return [
        { type: 'stream-start', warnings: [] },
        { type: 'text-start', id: 'local_text' },
        { type: 'text-delta', id: 'local_text', delta: content },
        { type: 'text-end', id: 'local_text' },
        finishChunk('stop'),
    ];
}

function finishChunk(reason: 'stop' | 'tool-calls'): LanguageModelV3StreamPart {
    return {
        type: 'finish',
        finishReason: { unified: reason, raw: undefined },
        usage: {
            inputTokens: { total: 0, noCache: 0, cacheRead: 0, cacheWrite: 0 },
            outputTokens: { total: 0, text: 0, reasoning: 0 },
        },
    };
}

function addFilePatch(path: string, fileContent: string): string {
    return [
        `diff --git a/${path} b/${path}`,
        '--- /dev/null',
        `+++ b/${path}`,
        '@@ -0,0 +1 @@',
        `+${fileContent}`,
        '',
    ].join('\n');
}

function readableStreamFromChunks(
    chunks: readonly LanguageModelV3StreamPart[],
): ReadableStream<LanguageModelV3StreamPart> {
    const remaining = [...chunks];
    return new ReadableStream<LanguageModelV3StreamPart>({
        pull(controller) {
            const next = remaining.shift();
            if (next === undefined) {
                controller.close();
                return;
            }
            controller.enqueue(next);
        },
    });
}
