export type RuntimeDbMigrationTableDescriptor = {
    readonly table: string;
    readonly columns: readonly string[];
    readonly keyColumns: readonly string[];
    readonly uniqueConstraints: readonly (readonly string[])[];
};

export const runtimeDbMigrationTableDescriptors: readonly RuntimeDbMigrationTableDescriptor[] = [
    {
        table: 'sessions',
        columns: [
            'session_id',
            'root_session_id',
            'parent_session_id',
            'status',
            'awaiting_reason',
            'primary_wait_id',
            'workspace_path',
            'provider_id',
            'model_id',
            'title',
            'total_input_tokens',
            'total_output_tokens',
            'total_cost_usd',
            'last_event_seq',
            'created_at',
            'updated_at',
            'last_activity_at',
            'stopped_at',
            'failed_at',
            'legacy_jsonl_path',
            'imported_at',
            'exported_at',
            'metadata_json',
        ],
        keyColumns: ['session_id'],
        uniqueConstraints: [],
    },
    {
        table: 'missions',
        columns: ['mission_id', 'status', 'workflow_name', 'created_at', 'updated_at', 'payload_json'],
        keyColumns: ['mission_id'],
        uniqueConstraints: [],
    },
    {
        table: 'session_event_sequences',
        columns: ['session_id', 'next_seq', 'updated_at'],
        keyColumns: ['session_id'],
        uniqueConstraints: [],
    },
    {
        table: 'session_events',
        columns: [
            'session_id',
            'seq',
            'event_id',
            'type',
            'timestamp',
            'run_id',
            'turn_id',
            'causation_id',
            'correlation_id',
            'payload_json',
        ],
        keyColumns: ['session_id', 'seq'],
        uniqueConstraints: [['event_id']],
    },
    {
        table: 'mission_runs',
        columns: [
            'run_id',
            'mission_id',
            'parent_run_id',
            'session_id',
            'child_agent_kind',
            'child_agent_id',
            'child_session_ids_json',
            'retry_state_json',
            'status',
            'prompt',
            'created_at',
            'updated_at',
            'started_at',
            'ended_at',
            'completed_at',
            'failed_at',
            'cancelled_at',
            'passthrough_json',
        ],
        keyColumns: ['run_id'],
        uniqueConstraints: [],
    },
    {
        table: 'session_inputs',
        columns: [
            'input_id',
            'session_id',
            'delivery',
            'status',
            'prompt',
            'admitted_seq',
            'promoted_seq',
            'created_at',
            'admitted_at',
            'promoted_at',
            'cancelled_at',
            'metadata_json',
        ],
        keyColumns: ['input_id'],
        uniqueConstraints: [],
    },
    {
        table: 'session_awaits',
        columns: [
            'wait_id',
            'session_id',
            'reason',
            'source_kind',
            'source_id',
            'run_id',
            'tool_call_id',
            'approval_id',
            'job_id',
            'child_session_id',
            'status',
            'created_at',
            'resolved_at',
            'cancelled_at',
            'metadata_json',
        ],
        keyColumns: ['wait_id'],
        uniqueConstraints: [],
    },
    {
        table: 'context_epochs',
        columns: [
            'context_epoch_id',
            'session_id',
            'epoch',
            'source_id',
            'baseline_text',
            'update_text',
            'created_at',
            'metadata_json',
        ],
        keyColumns: ['context_epoch_id'],
        uniqueConstraints: [['session_id', 'epoch', 'source_id']],
    },
    {
        table: 'session_relations',
        columns: ['relation_id', 'parent_session_id', 'child_session_id', 'kind', 'created_at', 'metadata_json'],
        keyColumns: ['relation_id'],
        uniqueConstraints: [['parent_session_id', 'child_session_id', 'kind']],
    },
    {
        table: 'runtime_agents',
        columns: [
            'agent_id',
            'kind',
            'session_id',
            'parent_agent_id',
            'status',
            'activity',
            'visibility',
            'created_at',
            'updated_at',
            'parked_at',
            'revived_at',
            'metadata_json',
        ],
        keyColumns: ['agent_id'],
        uniqueConstraints: [],
    },
    {
        table: 'async_jobs',
        columns: [
            'job_id',
            'parent_session_id',
            'child_session_id',
            'agent_id',
            'status',
            'queued_at',
            'started_at',
            'completed_at',
            'failed_at',
            'cancelled_at',
            'cancellation_reason',
            'result_json',
            'error_json',
            'metadata_json',
        ],
        keyColumns: ['job_id'],
        uniqueConstraints: [],
    },
    {
        table: 'legacy_session_imports',
        columns: [
            'import_id',
            'source_path',
            'source_kind',
            'checksum',
            'imported_event_count',
            'imported_at',
            'diagnostics_json',
        ],
        keyColumns: ['import_id'],
        uniqueConstraints: [['source_path', 'checksum']],
    },
    {
        table: 'memory_entries',
        columns: ['namespace', 'key', 'value', 'created_at', 'expires_at'],
        keyColumns: ['namespace', 'key'],
        uniqueConstraints: [],
    },
];
