import { renderToStaticMarkup } from 'react-dom/server';
import { describe, expect, it } from 'vitest';
import { App } from './App.js';
import type { DesktopSessionLog, DesktopSessionSummary } from './lib/agent-client.js';

describe('Desktop session inspector detail projection', () => {
    it('renders session timeline graph inspector branches approvals patch text and command output', () => {
        // Given
        const sessions: readonly DesktopSessionSummary[] = [
            {
                sessionId: 'session_task21',
                fileName: 'session_task21.jsonl',
                state: 'available',
                eventCount: 6,
                diagnostics: [],
            },
        ];
        const log: DesktopSessionLog = {
            sessionId: 'session_task21',
            state: 'available',
            contents: 'jsonl',
            diagnostics: [],
            envelopes: [
                envelope(0, {
                    type: 'prompt.admitted',
                    timestamp: '2026-06-09T00:00:00.000Z',
                    sessionId: 'session_task21',
                    message: 'queued prompt',
                    transcript: {
                        inputId: 'input_1',
                        messageId: 'message_1',
                        delivery: 'queue',
                        visibility: 'pending',
                    },
                }),
                envelope(1, {
                    type: 'approval.requested',
                    timestamp: '2026-06-09T00:00:01.000Z',
                    sessionId: 'session_task21',
                    message: 'approval requested',
                    approvalRecord: {
                        approvalId: 'approval_patch',
                        requestId: 'request_patch',
                        policyDecision: 'requires_approval',
                        state: 'pending',
                        subject: { kind: 'tool', id: 'file.patch' },
                        requestedAt: '2026-06-09T00:00:01.000Z',
                    },
                }),
                envelope(2, {
                    type: 'file.diff.proposed',
                    timestamp: '2026-06-09T00:00:02.000Z',
                    sessionId: 'session_task21',
                    message: 'diff proposed',
                    diffFiles: [
                        {
                            filePath: 'src/agent.ts',
                            changeKind: 'modified',
                            hunks: [
                                {
                                    oldStart: 1,
                                    oldLines: 1,
                                    newStart: 1,
                                    newLines: 1,
                                    lines: [{ kind: 'added', content: 'generated by mission-control' }],
                                },
                            ],
                        },
                    ],
                }),
                envelope(3, {
                    type: 'command.completed',
                    timestamp: '2026-06-09T00:00:03.000Z',
                    sessionId: 'session_task21',
                    message: 'command completed',
                    command: {
                        command: ['pnpm', 'test'],
                        cwd: '/repo',
                        status: 'completed',
                        exitCode: 0,
                    },
                }),
                envelope(4, {
                    type: 'node.completed',
                    timestamp: '2026-06-09T00:00:04.000Z',
                    sessionId: 'session_task21',
                    message: 'node completed',
                    abg: {
                        graphId: 'coding-agent',
                        nodeId: 'apply-patch',
                        signalType: 'success',
                    },
                }),
            ],
        };

        // When
        const html = renderToStaticMarkup(
            <App initialSessionId="session_task21" initialSessionSummaries={sessions} initialSessionLog={log} />,
        );

        // Then
        expect(html).toContain('Session timeline');
        expect(html).toContain('Graph inspector');
        expect(html).toContain('Branch navigator');
        expect(html).toContain('Approval queue');
        expect(html).toContain('Patch text');
        expect(html).toContain('Command output');
        expect(html).toContain('coding-agent');
        expect(html).toContain('apply-patch');
        expect(html).toContain('approval_patch');
        expect(html).toContain('src/agent.ts');
        expect(html).toContain('generated by mission-control');
        expect(html).toContain('pnpm test');
        expect(html).not.toContain('Start demo session');
    });
});

type EventInput = DesktopSessionLog['envelopes'][number]['event'];

function envelope(sequence: number, event: EventInput): DesktopSessionLog['envelopes'][number] {
    return {
        eventId: `event_${sequence}`,
        sequence,
        createdAt: event.timestamp,
        sessionId: 'session_task21',
        durability: 'durable',
        event,
    };
}
