import { renderToStaticMarkup } from 'react-dom/server';
import { describe, expect, it } from 'vitest';
import { App } from './App.js';
import type { DesktopSessionLog, DesktopSessionSummary } from './lib/agent-client.js';

describe('Desktop read-only session inspector', () => {
    it('renders session timeline graph inspector branches approvals patch text and command output', () => {
        // Given
        const sessions: readonly DesktopSessionSummary[] = [
            {
                sessionId: 'session_task21',
                fileName: 'session_task21.jsonl',
                state: 'available',
                eventCount: 6,
                diagnostics: [],
            },
        ];
        const log: DesktopSessionLog = {
            sessionId: 'session_task21',
            state: 'available',
            contents: 'jsonl',
            diagnostics: [],
            envelopes: [
                envelope(0, {
                    type: 'prompt.admitted',
                    timestamp: '2026-06-09T00:00:00.000Z',
                    sessionId: 'session_task21',
                    message: 'queued prompt',
                    transcript: {
                        inputId: 'input_1',
                        messageId: 'message_1',
                        delivery: 'queue',
                        visibility: 'pending',
                    },
                }),
                envelope(1, {
                    type: 'approval.requested',
                    timestamp: '2026-06-09T00:00:01.000Z',
                    sessionId: 'session_task21',
                    message: 'approval requested',
                    approvalRecord: {
                        approvalId: 'approval_patch',
                        requestId: 'request_patch',
                        policyDecision: 'requires_approval',
                        state: 'pending',
                        subject: { kind: 'tool', id: 'file.patch' },
                        requestedAt: '2026-06-09T00:00:01.000Z',
                    },
                }),
                envelope(2, {
                    type: 'file.diff.proposed',
                    timestamp: '2026-06-09T00:00:02.000Z',
                    sessionId: 'session_task21',
                    message: 'diff proposed',
                    diffFiles: [
                        {
                            filePath: 'src/agent.ts',
                            changeKind: 'modified',
                            hunks: [
                                {
                                    oldStart: 1,
                                    oldLines: 1,
                                    newStart: 1,
                                    newLines: 1,
                                    lines: [{ kind: 'added', content: 'generated by mission-control' }],
                                },
                            ],
                        },
                    ],
                }),
                envelope(3, {
                    type: 'command.completed',
                    timestamp: '2026-06-09T00:00:03.000Z',
                    sessionId: 'session_task21',
                    message: 'command completed',
                    command: {
                        command: ['pnpm', 'test'],
                        cwd: '/repo',
                        status: 'completed',
                        exitCode: 0,
                    },
                }),
                envelope(4, {
                    type: 'node.completed',
                    timestamp: '2026-06-09T00:00:04.000Z',
                    sessionId: 'session_task21',
                    message: 'node completed',
                    abg: {
                        graphId: 'coding-agent',
                        nodeId: 'apply-patch',
                        signalType: 'success',
                    },
                }),
            ],
        };

        // When
        const html = renderToStaticMarkup(
            <App initialSessionId="session_task21" initialSessionSummaries={sessions} initialSessionLog={log} />,
        );

        // Then
        expect(html).toContain('Session timeline');
        expect(html).toContain('Graph inspector');
        expect(html).toContain('Branch navigator');
        expect(html).toContain('Approval queue');
        expect(html).toContain('Patch text');
        expect(html).toContain('Command output');
        expect(html).toContain('coding-agent');
        expect(html).toContain('apply-patch');
        expect(html).toContain('approval_patch');
        expect(html).toContain('src/agent.ts');
        expect(html).toContain('generated by mission-control');
        expect(html).toContain('pnpm test');
        expect(html).not.toContain('Start demo session');
    });

    it('renders empty corrupt and missing states without crashing', () => {
        // Given
        const html = renderToStaticMarkup(
            <App
                initialSessionSummaries={[
                    {
                        sessionId: 'empty_session',
                        fileName: 'empty_session.jsonl',
                        state: 'empty',
                        eventCount: 0,
                        diagnostics: [],
                    },
                    {
                        sessionId: 'corrupt_session',
                        fileName: 'corrupt_session.jsonl',
                        state: 'corrupt',
                        eventCount: 1,
                        diagnostics: [{ code: 'corrupt_line', message: 'bad json', lineNumber: 3 }],
                    },
                    {
                        sessionId: 'missing_session',
                        fileName: 'missing_session.jsonl',
                        state: 'missing',
                        eventCount: 0,
                        diagnostics: [],
                    },
                ]}
                initialSessionLog={{
                    sessionId: 'corrupt_session',
                    state: 'corrupt',
                    contents: '',
                    envelopes: [],
                    diagnostics: [{ code: 'corrupt_line', message: 'bad json', lineNumber: 3 }],
                }}
            />,
        );

        // Then
        expect(html).toContain('empty_session');
        expect(html).toContain('corrupt_session');
        expect(html).toContain('missing_session');
        expect(html).toContain('bad json');
        expect(html).toContain('No timeline events');
    });

    it('renders loading and error state surfaces for the operational console', () => {
        // Given
        const html = renderToStaticMarkup(<App />);
        const errorHtml = renderToStaticMarkup(
            <App
                initialSessionSummaries={[
                    {
                        sessionId: 'corrupt_session',
                        fileName: 'corrupt_session.jsonl',
                        state: 'corrupt',
                        eventCount: 0,
                        diagnostics: [{ code: 'corrupt_line', message: 'bad json', lineNumber: 4 }],
                    },
                ]}
                initialSessionLog={{
                    sessionId: 'corrupt_session',
                    state: 'corrupt',
                    contents: '',
                    envelopes: [],
                    diagnostics: [{ code: 'corrupt_line', message: 'bad json', lineNumber: 4 }],
                }}
            />,
        );

        // Then
        expect(html).toContain('data-state="loading"');
        expect(html).toContain('Loading session catalog');
        expect(html).toContain('class="workspace-layout"');
        expect(html).toContain('class="utility-rail"');
        expect(errorHtml).toContain('class="source-status" data-state="error"');
        expect(errorHtml).toContain('corrupt session: 1 diagnostic');
        expect(errorHtml).toContain('data-state="corrupt"');
        expect(errorHtml).toContain('corrupt_line');
        expect(errorHtml).toContain('bad json');
    });

    it('does not project stale log rows when the selected session differs from the loaded log', () => {
        // Given
        const log: DesktopSessionLog = {
            sessionId: 'session_a',
            state: 'available',
            contents: 'jsonl',
            diagnostics: [],
            envelopes: [
                envelope(0, {
                    type: 'task.completed',
                    timestamp: '2026-06-09T00:00:00.000Z',
                    sessionId: 'session_a',
                    message: 'stale session event',
                }),
            ],
        };

        // When
        const html = renderToStaticMarkup(
            <App
                initialSessionId="session_b"
                initialSessionSummaries={[
                    {
                        sessionId: 'session_a',
                        fileName: 'session_a.jsonl',
                        state: 'available',
                        eventCount: 1,
                        diagnostics: [],
                    },
                    {
                        sessionId: 'session_b',
                        fileName: 'session_b.jsonl',
                        state: 'empty',
                        eventCount: 0,
                        diagnostics: [],
                    },
                ]}
                initialSessionLog={log}
            />,
        );

        // Then
        expect(html).toContain('session session_b');
        expect(html).toContain('No timeline events');
        expect(html).not.toContain('stale session event');
    });
});

type EventInput = DesktopSessionLog['envelopes'][number]['event'];

function envelope(sequence: number, event: EventInput): DesktopSessionLog['envelopes'][number] {
    return {
        eventId: `event_${sequence}`,
        sequence,
        createdAt: event.timestamp,
        sessionId: 'session_task21',
        durability: 'durable',
        event,
    };
}
