import type { GenerateImageInput, GenerateImageOutput, TtsInput, TtsOutput } from '@mission-control/protocol';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import {
    createEnvImageCredentialResolver,
    createGenerateImageToolRegistration,
    type GeneratedImageBytes,
    type GenerateImageToolOptions,
    type GenerateImageTransport,
    registerGenerateImageTool,
} from './generate-image-tool';
import { ToolExecutionError, ToolRegistry } from './tool-registry';
import { createTtsToolRegistration, registerTtsTool, type TtsToolOptions, type TtsTransport } from './tts-tool';
import { randomUUID } from 'node:crypto';
import { access, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

describe('generate_image + tts media seams (checkbox #33)', () => {
    const previous = captureEnv(['GEMINI_API_KEY', 'GOOGLE_API_KEY', 'OPENAI_API_KEY', 'XAI_API_KEY']);
    let artifactsDir: string;

    beforeEach(() => {
        previous.snapshot();
        artifactsDir = join(tmpdir(), `mctrl-media-test-${randomUUID()}`);
    });

    afterEach(async () => {
        previous.restore();
        await rm(artifactsDir, { recursive: true, force: true });
    });

    function imageOptions(overrides: Partial<GenerateImageToolOptions> = {}): GenerateImageToolOptions {
        return {
            sessionId: 'session-test',
            artifactsDir,
            credentialResolver: () =>
                Promise.resolve({ provider: 'gemini', apiKey: 'gemini-key', model: 'gemini-3-pro-image-preview' }),
            ...overrides,
        };
    }

    function ttsOptions(overrides: Partial<TtsToolOptions> = {}): TtsToolOptions {
        return {
            sessionId: 'session-test',
            credentialResolver: () => Promise.resolve({ apiKey: 'xai-key', baseURL: 'https://api.x.ai' }),
            ...overrides,
        };
    }

    function mockImageTransport(images: GeneratedImageBytes[]): GenerateImageTransport {
        return {
            async generate(input) {
                expect(input.prompt).toBeTruthy();
                return images;
            },
        };
    }

    describe('generate_image registration gate', () => {
        it('registers when a credential is configured', async () => {
            const registry = new ToolRegistry();
            const ad = await registerGenerateImageTool(registry, imageOptions());

            expect(ad?.name).toBe('generate_image');
            expect(registry.advertise().find((tool) => tool.name === 'generate_image')).toBeDefined();
        });

        it('skips registration (returns undefined) when no credential is configured', async () => {
            const registry = new ToolRegistry();
            const ad = await registerGenerateImageTool(registry, {
                sessionId: 'session-test',
                credentialResolver: () => Promise.resolve(undefined),
            });

            expect(ad).toBeUndefined();
            expect(registry.advertise().find((tool) => tool.name === 'generate_image')).toBeUndefined();
        });

        it('env resolver gates on GEMINI_API_KEY / OPENAI_API_KEY / XAI_API_KEY', async () => {
            const resolverGemini = createEnvImageCredentialResolver({ GEMINI_API_KEY: 'g' });
            const resolverOpenai = createEnvImageCredentialResolver({ OPENAI_API_KEY: 'o' });
            const resolverXai = createEnvImageCredentialResolver({ XAI_API_KEY: 'x' });
            const resolverEmpty = createEnvImageCredentialResolver({});

            expect((await resolverGemini())?.provider).toBe('gemini');
            expect((await resolverOpenai())?.provider).toBe('openai');
            expect((await resolverXai())?.provider).toBe('xai');
            expect(await resolverEmpty()).toBeUndefined();
        });
    });

    describe('generate_image execute', () => {
        it('writes generated bytes to the artifacts dir and returns paths only (media NOT inlined)', async () => {
            const pngBytes = new Uint8Array([0x89, 0x50, 0x4e, 0x47]);
            const registration = createGenerateImageToolRegistration(
                imageOptions({ transport: mockImageTransport([{ bytes: pngBytes, mimeType: 'image/png' }]) }),
            );
            const input: GenerateImageInput = { prompt: 'a red cube' };

            const output = await registration.execute(input, executionContext('generate_image'));

            expect(output.count).toBe(1);
            expect(output.provider).toBe('gemini');
            expect(output.image_paths).toHaveLength(1);
            const savedPath = output.image_paths[0]!;
            expect(savedPath.endsWith('.png')).toBe(true);

            // The path actually exists on disk with the right bytes.
            const onDisk = await readFile(savedPath);
            expect(Array.from(onDisk)).toEqual(Array.from(pngBytes));
        });

        it('serialized output contains no base64 media data (media NOT in events)', async () => {
            const pngBytes = new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a]);
            const registration = createGenerateImageToolRegistration(
                imageOptions({ transport: mockImageTransport([{ bytes: pngBytes, mimeType: 'image/png' }]) }),
            );
            const output = await registration.execute({ prompt: 'a blue sphere' }, executionContext('generate_image'));

            const serialized = JSON.stringify(output);
            // The base64 of the png bytes must never appear in the serialized output.
            const base64 = Buffer.from(pngBytes).toString('base64');
            expect(serialized).not.toContain(base64);
            // Only path-like string fields reference the artifact.
            expect(serialized).not.toMatch(/data:image/);
        });

        it('throws a non-retryable ToolExecutionError when the credential resolves to undefined', async () => {
            const registration = createGenerateImageToolRegistration({
                sessionId: 'session-test',
                artifactsDir,
                credentialResolver: () => Promise.resolve(undefined),
            });

            const caught = await captureError(() =>
                registration.execute({ prompt: 'x' }, executionContext('generate_image')),
            );

            expect(caught).toBeInstanceOf(ToolExecutionError);
            const error = caught as ToolExecutionError;
            expect(error.error.retryable).toBe(false);
            expect(error.error.message).toContain('GEMINI_API_KEY');
        });

        it('wraps transport failures as retryable ToolExecutionError', async () => {
            const registration = createGenerateImageToolRegistration(
                imageOptions({
                    transport: {
                        async generate() {
                            throw new Error('provider down');
                        },
                    },
                }),
            );

            const caught = await captureError(() =>
                registration.execute({ prompt: 'x' }, executionContext('generate_image')),
            );

            expect(caught).toBeInstanceOf(ToolExecutionError);
            const error = caught as ToolExecutionError;
            expect(error.error.retryable).toBe(true);
            expect(error.error.message).toContain('provider down');
        });

        it('toModelOutput lists paths without inlining bytes', () => {
            const registration = createGenerateImageToolRegistration(imageOptions());
            const output: GenerateImageOutput = {
                image_paths: ['/tmp/artifacts/a.png', '/tmp/artifacts/b.png'],
                provider: 'xai',
                model: 'grok-imagine-image',
                count: 2,
            };

            const text = registration.toModelOutput?.(output) ?? '';

            expect(text).toContain('/tmp/artifacts/a.png');
            expect(text).toContain('/tmp/artifacts/b.png');
            expect(text).toContain('xai');
            expect(text).not.toMatch(/data:image/);
        });
    });

    describe('tts registration gate', () => {
        it('registers when XAI_API_KEY is set', async () => {
            const registry = new ToolRegistry();
            const ad = await registerTtsTool(registry, ttsOptions());

            expect(ad?.name).toBe('tts');
            expect(registry.advertise().find((tool) => tool.name === 'tts')).toBeDefined();
        });

        it('skips registration when no xAI credential is configured', async () => {
            const registry = new ToolRegistry();
            const ad = await registerTtsTool(registry, {
                sessionId: 'session-test',
                credentialResolver: () => Promise.resolve(undefined),
            });

            expect(ad).toBeUndefined();
            expect(registry.advertise().find((tool) => tool.name === 'tts')).toBeUndefined();
        });
    });

    describe('tts execute', () => {
        function mockTtsTransport(bytes: Uint8Array): TtsTransport {
            return {
                async synthesize(input) {
                    expect(input.text.length).toBeGreaterThan(0);
                    return { bytes, codec: input.codec };
                },
            };
        }

        it('writes audio bytes to output_path and returns the path only (media NOT inlined)', async () => {
            const audioBytes = new Uint8Array([0x52, 0x49, 0x46, 0x46]); // RIFF header
            const registration = createTtsToolRegistration(ttsOptions({ transport: mockTtsTransport(audioBytes) }));
            const outputPath = join(artifactsDir, 'clip.wav');
            const input: TtsInput = {
                text: 'hello world',
                voice_id: 'eve',
                language: 'en',
                output_path: outputPath,
            };

            const output = await registration.execute(input, executionContext('tts'));

            expect(output.audio_path).toBe(outputPath);
            expect(output.bytes).toBe(audioBytes.byteLength);
            expect(output.codec).toBe('wav');
            expect(output.backend).toBe('xai');
            // The file exists with the right bytes.
            const onDisk = await readFile(outputPath);
            expect(Array.from(onDisk)).toEqual(Array.from(audioBytes));
        });

        it('serialized output contains no base64 audio data (media NOT in events)', async () => {
            const audioBytes = new Uint8Array([0x52, 0x49, 0x46, 0x46, 0xaa, 0xbb]);
            const registration = createTtsToolRegistration(ttsOptions({ transport: mockTtsTransport(audioBytes) }));
            const input: TtsInput = {
                text: 'no inline media',
                voice_id: 'rex',
                language: 'en',
                output_path: join(artifactsDir, 'clip2.wav'),
            };

            const output = await registration.execute(input, executionContext('tts'));

            const serialized = JSON.stringify(output);
            const base64 = Buffer.from(audioBytes).toString('base64');
            expect(serialized).not.toContain(base64);
            expect(serialized).not.toMatch(/data:audio/);
        });

        it('throws a non-retryable ToolExecutionError when the credential resolves to undefined', async () => {
            const registration = createTtsToolRegistration({
                sessionId: 'session-test',
                credentialResolver: () => Promise.resolve(undefined),
            });

            const caught = await captureError(() =>
                registration.execute(
                    { text: 'hi', voice_id: 'eve', language: 'en', output_path: join(artifactsDir, 'x.wav') },
                    executionContext('tts'),
                ),
            );

            expect(caught).toBeInstanceOf(ToolExecutionError);
            const error = caught as ToolExecutionError;
            expect(error.error.retryable).toBe(false);
            expect(error.error.message).toContain('XAI_API_KEY');
        });

        it('artifacts dir is created when missing', async () => {
            const registration = createTtsToolRegistration(
                ttsOptions({ transport: mockTtsTransport(new Uint8Array([1, 2, 3])) }),
            );
            const nestedOutput = join(artifactsDir, 'nested', 'deep', 'clip.mp3');

            await registration.execute(
                { text: 'nested', voice_id: 'leo', language: 'en', output_path: nestedOutput },
                executionContext('tts'),
            );

            await expect(access(nestedOutput)).resolves.toBeUndefined();
        });
    });

    function executionContext(toolName: string) {
        return {
            toolCallId: `${toolName}-call`,
            toolName,
            signal: new AbortController().signal,
        };
    }

    async function captureError(thunk: () => unknown | Promise<unknown>): Promise<unknown> {
        try {
            await thunk();
        } catch (error: unknown) {
            return error;
        }
        throw new Error('expected execute to throw');
    }

    function captureEnv(names: readonly string[]) {
        const snapshot = new Map<string, string | undefined>();
        for (const name of names) snapshot.set(name, process.env[name]);
        return {
            snapshot() {
                for (const name of names) delete process.env[name];
            },
            restore() {
                for (const name of names) {
                    const value = snapshot.get(name);
                    if (value === undefined) delete process.env[name];
                    else process.env[name] = value;
                }
            },
        };
    }
});
