-- Historical session-index sketch retained for old doc links.
--
-- Authoritative local SQLite/libSQL session event/replay sources:
--   packages/core/src/db/session-*-schema.ts
--   packages/core/src/db/local-libsql-schema*.ts
--   packages/core/src/memory/sqlite-session-event-store*.ts
--   packages/core/src/memory/sqlite-session-projection*.ts
--
-- See docs/session-data-model.md for table responsibilities, key indexes,
-- awaiting/session_awaits semantics, the data-dir memory.db public projection,
-- legacy_session_imports, import/export operation, and operational behavior.
--
-- New session event/replay writes use the local libSQL database at
-- <MCTRL_DATA_DIR>/memory.db.
-- Legacy JSONL files are compatibility import/export artifacts, not the new
-- authoritative write path. Blocking user_input and foreground subagent waits
-- surface through the public memory.db projection. Remote Turso is out of scope.
